from fastapi import FastAPI, Depends, HTTPException, status
from sqlalchemy.orm import Session

from database import get_db
from models import Employee, LeaveRequest, LeaveStatus
from schemas import (
    EmployeeOut,
    LeaveRequestOut,
    LeaveRequestCreate,
    LeaveRequestUpdate,
)

app = FastAPI()


@app.get("/")
def root():
    return {"message": "Leave Request Tracker API"}


# ---------- Employees ----------

@app.get("/employees", response_model=list[EmployeeOut])
def list_employees(db: Session = Depends(get_db)):
    return db.query(Employee).all()


# ---------- Leave requests ----------

@app.get("/leave-requests", response_model=list[LeaveRequestOut])
def list_leave_requests(
    db: Session = Depends(get_db),
    employee_id: int | None = None,
    status: LeaveStatus | None = None,
    skip: int = 0,
    limit: int = 10,
):
    query = db.query(LeaveRequest)

    if employee_id is not None:
        query = query.filter(LeaveRequest.employee_id == employee_id)
    if status is not None:
        query = query.filter(LeaveRequest.status == status)

    return query.offset(skip).limit(limit).all()


@app.post("/leave-requests", response_model=LeaveRequestOut,
          status_code=status.HTTP_201_CREATED)
def create_leave_request(payload: LeaveRequestCreate, db: Session = Depends(get_db)):
    # The employee must exist first -> return a clear 404 instead of letting
    # the database raise an integrity error (which would surface as a 500).
    employee = db.query(Employee).filter(Employee.id == payload.employee_id).first()
    if employee is None:
        raise HTTPException(status_code=404, detail="Employee not found")

    # id is generated by the DB; status is set by the server (always DRAFT).
    new_request = LeaveRequest(
        employee_id=payload.employee_id,
        leave_type=payload.leave_type,
        start_date=payload.start_date,
        end_date=payload.end_date,
        reason=payload.reason,
        status=LeaveStatus.DRAFT,
    )
    db.add(new_request)       # stage the row
    db.commit()               # save it
    db.refresh(new_request)   # reload so the DB-generated id is populated
    return new_request


@app.patch("/leave-requests/{id}", response_model=LeaveRequestOut)
def update_leave_request(id: int, payload: LeaveRequestUpdate, db: Session = Depends(get_db)):
    # {id} comes from the URL; FastAPI passes it in as the id argument.
    leave_request = db.query(LeaveRequest).filter(LeaveRequest.id == id).first()
    if leave_request is None:
        raise HTTPException(status_code=404, detail="Leave request not found")

    # DRAFT guard: once a request leaves draft, it can no longer be edited.
    if leave_request.status != LeaveStatus.DRAFT:
        raise HTTPException(status_code=409, detail="Only draft requests can be edited.")

    update_data = payload.model_dump(exclude_unset=True)

    # Validate the MERGED dates -- what the row WILL look like after the edit,
    # not just what the client sent. A partial PATCH may carry only one date,
    # so fall back to the existing value for whichever one is absent.
    new_start = update_data.get("start_date", leave_request.start_date)
    new_end = update_data.get("end_date", leave_request.end_date)
    if new_end < new_start:
        raise HTTPException(status_code=422, detail="end_date cannot be before start_date")

    # Apply ONLY the fields the client actually sent (partial update).
    for field, value in update_data.items():
        setattr(leave_request, field, value)

    db.commit()
    db.refresh(leave_request)
    return leave_request


@app.post("/leave-requests/{id}/submit", response_model=LeaveRequestOut)
def submit_leave_request(id: int, db: Session = Depends(get_db)):
    leave_request = db.query(LeaveRequest).filter(LeaveRequest.id == id).first()
    if leave_request is None:
        raise HTTPException(status_code=404, detail="Leave request not found")

    # Status guard: submit is only legal from DRAFT.
    if leave_request.status != LeaveStatus.DRAFT:
        raise HTTPException(status_code=409, detail="Only draft requests can be submitted")

    # The deferred reason rule, finally enforced. `not` catches None AND "".
    if not leave_request.reason:
        raise HTTPException(status_code=422, detail="A reason is required to submit")

    leave_request.status = LeaveStatus.SUBMITTED
    db.commit()
    db.refresh(leave_request)
    return leave_request


@app.post("/leave-requests/{id}/reject", response_model=LeaveRequestOut)
def reject_leave_request(id: int, db: Session = Depends(get_db)):
    leave_request = db.query(LeaveRequest).filter(LeaveRequest.id == id).first()
    if leave_request is None:
        raise HTTPException(status_code=404, detail="Leave request not found")

    # reject is only legal from SUBMITTED.
    if leave_request.status != LeaveStatus.SUBMITTED:
        raise HTTPException(status_code=409, detail="Only submitted requests can be rejected")

    leave_request.status = LeaveStatus.REJECTED
    db.commit()
    db.refresh(leave_request)
    return leave_request


@app.post("/leave-requests/{id}/cancel", response_model=LeaveRequestOut)
def cancel_leave_request(id: int, db: Session = Depends(get_db)):
    leave_request = db.query(LeaveRequest).filter(LeaveRequest.id == id).first()
    if leave_request is None:
        raise HTTPException(status_code=404, detail="Leave request not found")

    # cancel is legal from two source states: DRAFT or SUBMITTED.
    if leave_request.status not in (LeaveStatus.DRAFT, LeaveStatus.SUBMITTED):
        raise HTTPException(status_code=409, detail="Only draft or submitted requests can be cancelled")

    leave_request.status = LeaveStatus.CANCELLED
    db.commit()
    db.refresh(leave_request)
    return leave_request


@app.post("/leave-requests/{id}/approve", response_model=LeaveRequestOut)
def approve_leave_request(id: int, db: Session = Depends(get_db)):
    leave_request = db.query(LeaveRequest).filter(LeaveRequest.id == id).first()
    if leave_request is None:
        raise HTTPException(status_code=404, detail="Leave request not found")

    # approve is only legal from SUBMITTED.
    if leave_request.status != LeaveStatus.SUBMITTED:
        raise HTTPException(status_code=409, detail="Only submitted requests can be approved")

    # Overlap rule: no two APPROVED leaves for the same employee may share dates.
    # Two ranges overlap when:  existing.start <= this.end  AND  this.start <= existing.end
    # Here LeaveRequest.* = the existing approved row (DB column);
    #      leave_request.* = the request being approved (Python object).
    conflict = (
        db.query(LeaveRequest)
        .filter(
            LeaveRequest.employee_id == leave_request.employee_id,
            LeaveRequest.status == LeaveStatus.APPROVED,
            LeaveRequest.start_date <= leave_request.end_date,
            leave_request.start_date <= LeaveRequest.end_date,
            LeaveRequest.id != leave_request.id,  # defensive: never clash with self
        )
        .first()
    )
    if conflict is not None:
        raise HTTPException(
            status_code=409,
            detail="Overlaps an existing approved leave for this employee",
        )

    leave_request.status = LeaveStatus.APPROVED
    db.commit()
    db.refresh(leave_request)
    return leave_request